title: "Liz Wigglesworth"
description: "developer & cybersecurity enthusiast"
author: "Liz Wigglesworth"

url: "https://www.lizwigg.com" # the base hostname & protocol for the site, e.g. http://example.com
baseurl: "/" # the subpath , e.g. /blog

plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /blog/:title
  portfolio:
    output: true
    permalink: /:collection/:title