#
###################################
# Site wide configuration
####################################
#
title: lizgw
email:
description: A simple and awesome blog theme powered by jekyll.
url: https://lizgw.github.io/
keywords: ["blog", "jekyll", "programming", "design"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /blog/:year/:month/:title

collections:
  portfolio_items:
    output: true
    permalink: /portfolio/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Liz Wigglesworth
  avatar: 
  job: 
  bio: programmer & designer
  email:
  disqus-shortname:
  twitter: lizgwigg
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: lizgw
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
