# Site wide configuration

title: lizgw
locale: en_US
description: "I'm Liz Wigglesworth: programmer, designer & high school student."
logo: site-logo.png
search: true
url: #http://lizgw.github.io

# Jekyll configuration
collections:
  designs:
    output: true
    permalink: /portfolio/designs/:year/:title/
  codeprojects:
    output: true
    permalink: /portfolio/code/:title/

# Pagination
permalink: /blog/:categories/:year/:month/:day/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Liz Wigglesworth
  avatar: bio-photo.jpg
  email: 
  disqus-shortname:
  twitter: lizgwigg
  github: lizgw
  instagram: lizgwigg
  flickr: #username
  google:
    plus: #username
    analytics: UA-63911647-1
    verify:
    ad-client:
    ad-slot:
