title: "lizgw"

url: "" # the base hostname & protocol for the site, e.g. http://example.com
baseurl: "/" # the subpath , e.g. /blog

collections:
  posts:
    output: true
    permalink: /blog/:title
  portfolio:
    output: true
    permalink: /:collection/:title